package com.udemy.learn.blogging.utils;
import java.awt.Color;
import java.io.IOException;
import java.util.List;
 
import jakarta.servlet.http.HttpServletResponse;
 
import com.lowagie.text.*;
import com.lowagie.text.pdf.*;
import com.udemy.learn.blogging.entity.Post;
 
 
public class UserPDFExporter {
    private List<Post> listPost;
     
    public UserPDFExporter(List<Post> listPost) {
        this.listPost = listPost;
    }
 
    private void writeTableHeader(PdfPTable table) {
        PdfPCell cell = new PdfPCell();
        cell.setBackgroundColor(Color.BLUE);
        cell.setPadding(5);
         
        Font font = FontFactory.getFont(FontFactory.HELVETICA);
        font.setColor(Color.WHITE);
         
        cell.setPhrase(new Phrase("Post ID", font));
         
        table.addCell(cell);
         
        cell.setPhrase(new Phrase("Title", font));
        table.addCell(cell);
         
        cell.setPhrase(new Phrase("Author", font));
        table.addCell(cell);
         
        cell.setPhrase(new Phrase("Desciption", font));
        table.addCell(cell);
         
        cell.setPhrase(new Phrase("Content", font));
        table.addCell(cell);       
    }
     
    private void writeTableData(PdfPTable table) {
        for (Post post : listPost) {
            table.addCell(String.valueOf(post.getId()));
            table.addCell(String.valueOf((post.getTitle())));
            table.addCell(String.valueOf((post.getAuthor().getName())));
            table.addCell(String.valueOf((post.getDescription())));
            table.addCell(String.valueOf((post.getCategory().getName())));
        }
    }
     
    public void export(HttpServletResponse response) throws DocumentException, IOException {
        Document document = new Document(PageSize.A4);
        PdfWriter.getInstance(document, response.getOutputStream());
         
        document.open();
        Font font = FontFactory.getFont(FontFactory.TIMES_BOLD);
        Font f1=FontFactory.getFont(FontFactory.TIMES_BOLDITALIC);
        font.setSize(18);
        font.setColor(Color.BLUE);
        Paragraph p1=new Paragraph("A pdf generated by SarojDaikoBlog Website");
         
        Paragraph p = new Paragraph("List of Users", f1);
        p.setAlignment(Paragraph.ALIGN_CENTER);
        document.add(p1); 
        document.add(p);
  
         
        PdfPTable table = new PdfPTable(5);
        table.setWidthPercentage(100f);
        table.setWidths(new float[] {1.5f, 3.5f, 3.0f, 3.0f, 1.5f});
        table.setSpacingBefore(10);
         
        writeTableHeader(table);
        writeTableData(table);
         
        document.add(table);
         
        document.close();
         
    }
}